### ISSUE TITLE
vimdoc can not generate doc for func.

### ISSUE THREAD

**Issue by wsdjeg** [google/vimdoc#93]
Hi @dbarnett , Thanks for your project. I just want use it for my new libs,https://github.com/wsdjeg/GitHub-api.vim but as you can see in this repo, only can generate doc for a g:var. 
I just run `vimdoc .` in the root dir of the repo. still does not work.

**Comment by dbarnett** [comment]
Your problem is that your functions aren't marked as `@public`, and the functions are private by default because the plugin isn't marked as `@library` even though it looks like a library plugin.

BTW, plugin/ files in a library plugin probably won't behave how you want; you may want to initialize that variable differently, in autoload files.

**Comment by wsdjeg** [comment]
@dbarnett thanks a lot, but I have a new question about vimdoc, https://github.com/wsdjeg/GitHub-api.vim/issues/2, thanks.
